language: python
python:
  - 2.7
env:
  - DJANGO=1.6
  - DJANGO=1.6.1
  - DJANGO=1.6.5
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install . --use-mirrors
script:
  - python manage.py test logicaldelete
matrix:
  exclude:
    # Django doesn't support following combinations
    - python: 3.2
      env: DJANGO=1.4.10
    - python: 3.3
      env: DJANGO=1.4.10